import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvdier from "@/redux/StoreProvdier";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvdier>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </StoreProvdier>
  );
}
